/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ControlParentalRouteImport } from './routes/control-parental'
import { Route as IndexRouteImport } from './routes/index'

const ControlParentalRoute = ControlParentalRouteImport.update({
  id: '/control-parental',
  path: '/control-parental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-parental': typeof ControlParentalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-parental': typeof ControlParentalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-parental': typeof ControlParentalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control-parental'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control-parental'
  id: '__root__' | '/' | '/control-parental'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlParentalRoute: typeof ControlParentalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/control-parental': {
      id: '/control-parental'
      path: '/control-parental'
      fullPath: '/control-parental'
      preLoaderRoute: typeof ControlParentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlParentalRoute: ControlParentalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
